---
# tasks file for oem
- name: Ensure this in Linux Mint
  assert:
      that:
        - "ansible_distribution == 'Linuxmint' or ansible_distribution == 'Linux Mint'"
- name: Update apt cache
  apt:
      update_cache: yes
- name: Remove unneeded stock packages
  apt: name={{ item }} state=absent purge=yes
  with_items: '{{ packages_to_remove }}'
- name: Remove unused dependencies
  apt:
      # A name must be specified in Ansible 2.1.1.0 or you get a cryptic error
      # message when running the playbook. This will not remove the curl package.
      # It was chosen arbitrarily just to allow this playbook to run
      name: curl
      autoremove: yes
- name: Upgrade all installed packages
  apt:
      upgrade: safe
- name: Install dependencies
  apt:
      name: "{{ item }}"
      state: latest
  with_items: '{{ packages_to_install }}'
- name: Clean the apt database
  command: apt-get clean
  # This will always report as changed otherwise
  changed_when: False
  args:
    warn: no
- name: Ensure skeleton Desktop directory exists
  file:
      path: /etc/skel/Desktop
      state: directory
      mode: 0750
- name: Ensure log directory exists
  file:
      path: /opt/vmtools/logs
      state: directory
      mode: 0755
- name: Copy welcome shortcut to skeleton desktop directory
  copy:
      src: welcome-to-vm.desktop
      dest: /etc/skel/Desktop/welcome-to-vm.desktop
      mode: 0644
- name: Hide the mintwelcome window
  file:
      path: /etc/skel/.linuxmint/mintwelcome
      mode: 0755
      state: directory
- name: Hide the mintwelcome window
  file:
      path: /etc/skel/.linuxmint/mintwelcome/norun.flag
      mode: 0664
      state: touch
- name: Create the /usr/local/share/applications folder
  file:
      path: /usr/local/share/applications
      state: directory
      mode: 0755
      owner: root
      group: staff
